# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ad9d7v4mGbrmWTFAHwJ2hSCI5vZnLR8U
"""

import re
import csv

class Studentbit:
  def __init__(self, sid, sname, marks, fm, fg):
    self.sid  = sid
    self.sname = sname
    self.marks = marks
    self.fm = fm
    self.fg = fg
    self.typ = "BIT"

class Studentdit:
  def __init__(self, sid, sname, fm, fg):
    self.sid  = sid
    self.sname = sname
    self.fm = fm
    self.fg = fg
    self.typ = "DIT"

sid = input("\nEnter student ID:")
if not re.match("^[A][0-9]{8}$", sid):
  print ("\nError! Invalid student ID!")
  quit()
  
sname = input("Enter student Name:")
if not re.match("[A-Za-z]", sname):
  print("\nError! Only letters a-z allowed for name!")
  quit()
  
abcnt = 0
fcnt = 0
  
marks = [int(x) for x in input("\nEnter student assessment marks (separated by comma):").split(',')]
for m in marks:
  if m == 0:
    abcnt += 1
  if m < 50:
    fcnt += 1
  if not re.match("^(?:100(?:[.,]00?)?|\d?\d(?:[.,]\d\d?)?)$", str(m)):
    print("\nError! Only Numbers allowed for marks!")
    quit()
  
fm = marks[0]*0.2 + marks[1]*0.4 + marks[2]*0.4
  
if(fm<=100 and fm>=85):
    fg = 'HD'
elif(fm<=84 and fm>=75):
    fg = 'D'
elif(fm<=74 and fm>=65):
    fg = 'C'
elif(fm<=64 and fm>=50):
    fg = 'P'
  
elif(fm<=49 and fm>=45 and abcnt == 0 and fcnt == 1):
  if (marks[0] < 50):
    supp1 = int(input("\nWhat is this student’s supplementary exam mark:"))
    if not re.match("^(?:100(?:[.,]00?)?|\d?\d(?:[.,]\d\d?)?)$", str(supp1)):
      print("\nError! Only Numbers allowed for marks!")
      quit()
    marks[0] = supp1

elif (marks[1] < 50):
  supp2 = int(input("\nWhat is this student’s supplementary exam mark:"))
  if not re.match("^(?:100(?:[.,]00?)?|\d?\d(?:[.,]\d\d?)?)$", str(supp2)):
    print("\nError! Only Numbers allowed for marks!")
    quit()
  marks[1] = supp2
      
elif (marks[2] < 50):
  supp3 = int(input("\nWhat is this student’s supplementary exam mark:"))
  if not re.match("^(?:100(?:[.,]00?)?|\d?\d(?:[.,]\d\d?)?)$", str(supp3)):
    print("\nError! Only Numbers allowed for marks!")
    quit()
  marks[2] = supp3
      
  supp = marks[0]*0.2 + marks[1]*0.4 + marks[2]*0.4

  if supp >= 50:
    fg = 'SP'
  else:
      fg ='F'
else:
    fg = 'AF'
  
s = Studentbit(sid, sname ,marks, fm, fg)
  
print(s)